// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourceInfo is the per-source row the Sources view renders.
 */
export interface SourceInfo {
    "name": string;
    "kind": string;
    "enabled": boolean;
    "detected": boolean;
    "deviceCount": number;
    "capabilities": string[] | null;
    "driverVersions": string[] | null;
}
