// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SourceInfo is the per-source row the Sources view renders.
 */
export class SourceInfo {
    /**
     * Creates a new SourceInfo instance.
     * @param {Partial<SourceInfo>} [$$source = {}] - The source object to create the SourceInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detected"] = false;
        }
        if (!("deviceCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deviceCount"] = 0;
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["capabilities"] = [];
        }
        if (!("driverVersions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["driverVersions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField5_0($$parsedSource["capabilities"]);
        }
        if ("driverVersions" in $$parsedSource) {
            $$parsedSource["driverVersions"] = $$createField6_0($$parsedSource["driverVersions"]);
        }
        return new SourceInfo(/** @type {Partial<SourceInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
