// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes the accelerator registry's source toggles and capability
 * matrix to the frontend. It is re-registered as a Wails service in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.SourceInfo[]>}
 */
export function ListSources() {
    return $Call.ByID(2881595370).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetCapability disabled/enables a capability globally across sources.
 * @param {string} capability
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetCapability(capability, enabled) {
    return $Call.ByID(1557796718, capability, enabled);
}

/**
 * SetSourceEnabled toggles a source and re-runs detection so DetectedSources /
 * SampleAll reflect the change immediately.
 * @param {string} name
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetSourceEnabled(name, enabled) {
    return $Call.ByID(387417294, name, enabled);
}

// Private type creation functions
const $$createType0 = $models.SourceInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
