// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes the accelerator registry's source toggles and capability
 * matrix to the frontend. It is re-registered as a Wails service in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListSources(): $CancellablePromise<$models.SourceInfo[] | null> {
    return $Call.ByID(2881595370);
}

/**
 * SetCapability disabled/enables a capability globally across sources.
 */
export function SetCapability(capability: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1557796718, capability, enabled);
}

/**
 * SetSourceEnabled toggles a source and re-runs detection so DetectedSources /
 * SampleAll reflect the change immediately.
 */
export function SetSourceEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(387417294, name, enabled);
}
