// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Point is one sampled snapshot for a single device.
 */
export class Point {
    /**
     * Creates a new Point instance.
     * @param {Partial<Point>} [$$source = {}] - The source object to create the Point.
     */
    constructor($$source = {}) {
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }
        if (!("utilPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["utilPct"] = 0;
        }
        if (!("vramUsed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vramUsed"] = 0;
        }
        if (!("vramTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vramTotal"] = 0;
        }
        if (!("tempC" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tempC"] = 0;
        }
        if (!("powerW" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["powerW"] = 0;
        }
        if (!("clockMhz" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clockMhz"] = 0;
        }
        if (!("fanPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fanPct"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Point}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point(/** @type {Partial<Point>} */($$parsedSource));
    }
}
