// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Point is one sampled snapshot for a single device.
 */
export interface Point {
    "ts": number;
    "utilPct": number;
    "vramUsed": number;
    "vramTotal": number;
    "tempC": number;
    "powerW": number;
    "clockMhz": number;
    "fanPct": number;
}
