// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service keeps an in-memory ring buffer of samples per device. It is fed from
 * the metrics.Service via AddSink and queried through Range/Export bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accelerator$0 from "../accelerator/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bounds returns the retention window in seconds.
 * @returns {$CancellablePromise<number>}
 */
export function Bounds() {
    return $Call.ByID(248914198);
}

/**
 * Devices returns the device IDs that have at least one sample, in first-seen
 * order.
 * @returns {$CancellablePromise<string[]>}
 */
export function Devices() {
    return $Call.ByID(2985903622).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExportCSV renders a device series (or the last `seconds`) as CSV with a
 * header row suitable for spreadsheets.
 * @param {string} device
 * @param {number} seconds
 * @returns {$CancellablePromise<string>}
 */
export function ExportCSV(device, seconds) {
    return $Call.ByID(1420857579, device, seconds);
}

/**
 * ExportJSON returns the last `seconds` of points for a device as a JSON array
 * (stable ordering by timestamp).
 * @param {string} device
 * @param {number} seconds
 * @returns {$CancellablePromise<string>}
 */
export function ExportJSON(device, seconds) {
    return $Call.ByID(1691145615, device, seconds);
}

/**
 * Ingest records one Sample into the per-device series and drops the oldest
 * point when the ring exceeds capacity.
 * @param {accelerator$0.Sample} sample
 * @returns {$CancellablePromise<void>}
 */
export function Ingest(sample) {
    return $Call.ByID(2339643151, sample);
}

/**
 * Range returns the most recent `seconds` of points for a device (empty slice
 * when the device is unknown).
 * @param {string} device
 * @param {number} seconds
 * @returns {$CancellablePromise<$models.Point[]>}
 */
export function Range(device, seconds) {
    return $Call.ByID(3917887184, device, seconds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.Point.createFrom;
const $$createType2 = $Create.Array($$createType1);
