// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service keeps an in-memory ring buffer of samples per device. It is fed from
 * the metrics.Service via AddSink and queried through Range/Export bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accelerator$0 from "../accelerator/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bounds returns the retention window in seconds.
 */
export function Bounds(): $CancellablePromise<number> {
    return $Call.ByID(248914198);
}

/**
 * Devices returns the device IDs that have at least one sample, in first-seen
 * order.
 */
export function Devices(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2985903622);
}

/**
 * ExportCSV renders a device series (or the last `seconds`) as CSV with a
 * header row suitable for spreadsheets.
 */
export function ExportCSV(device: string, seconds: number): $CancellablePromise<string> {
    return $Call.ByID(1420857579, device, seconds);
}

/**
 * ExportJSON returns the last `seconds` of points for a device as a JSON array
 * (stable ordering by timestamp).
 */
export function ExportJSON(device: string, seconds: number): $CancellablePromise<string> {
    return $Call.ByID(1691145615, device, seconds);
}

/**
 * Ingest records one Sample into the per-device series and drops the oldest
 * point when the ring exceeds capacity.
 */
export function Ingest(sample: accelerator$0.Sample): $CancellablePromise<void> {
    return $Call.ByID(2339643151, sample);
}

/**
 * Range returns the most recent `seconds` of points for a device (empty slice
 * when the device is unknown).
 */
export function Range(device: string, seconds: number): $CancellablePromise<$models.Point[] | null> {
    return $Call.ByID(3917887184, device, seconds);
}
