// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Engine evaluates rules against each Sample. It survives UI restarts: rules
 * are persisted to a JSON store, evaluation runs in Go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accelerator$0 from "../accelerator/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function AcknowledgeAll() {
    return $Call.ByID(611910056);
}

/**
 * @returns {$CancellablePromise<$models.Fire[]>}
 */
export function ActiveFires() {
    return $Call.ByID(2662434882).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRule(id) {
    return $Call.ByID(2441727778, id);
}

/**
 * Evaluate processes a Sample and returns any fires it produced (also stored
 * in ActiveFires). Concurrency-safe; call from the metrics sink goroutine.
 * @param {accelerator$0.Sample} sample
 * @returns {$CancellablePromise<$models.Fire[]>}
 */
export function Evaluate(sample) {
    return $Call.ByID(3148139888, sample).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Rule[]>}
 */
export function Rules() {
    return $Call.ByID(319809942).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetRuleEnabled(id, on) {
    return $Call.ByID(4222749672, id, on);
}

/**
 * @param {$models.Rule} r
 * @returns {$CancellablePromise<void>}
 */
export function UpsertRule(r) {
    return $Call.ByID(2540111290, r);
}

// Private type creation functions
const $$createType0 = $models.Fire.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Rule.createFrom;
const $$createType3 = $Create.Array($$createType2);
