// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Engine evaluates rules against each Sample. It survives UI restarts: rules
 * are persisted to a JSON store, evaluation runs in Go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accelerator$0 from "../accelerator/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcknowledgeAll(): $CancellablePromise<void> {
    return $Call.ByID(611910056);
}

export function ActiveFires(): $CancellablePromise<$models.Fire[] | null> {
    return $Call.ByID(2662434882);
}

export function DeleteRule(id: string): $CancellablePromise<void> {
    return $Call.ByID(2441727778, id);
}

/**
 * Evaluate processes a Sample and returns any fires it produced (also stored
 * in ActiveFires). Concurrency-safe; call from the metrics sink goroutine.
 */
export function Evaluate(sample: accelerator$0.Sample): $CancellablePromise<$models.Fire[] | null> {
    return $Call.ByID(3148139888, sample);
}

export function Rules(): $CancellablePromise<$models.Rule[] | null> {
    return $Call.ByID(319809942);
}

export function SetRuleEnabled(id: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(4222749672, id, on);
}

export function UpsertRule(r: $models.Rule): $CancellablePromise<void> {
    return $Call.ByID(2540111290, r);
}
