// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action is what an alert does when it fires.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * in-app toast (frontend renders)
     */
    ActionToast = "toast",

    /**
     * desktop notification
     */
    ActionNotify = "notify",

    /**
     * suspend offender (zombie)
     */
    ActionAutoSuspend = "auto-suspend",

    /**
     * kill offender (zombie, double-confirm in future)
     */
    ActionAutoTerminate = "auto-terminate",
};

/**
 * Fire is an emitted alert (surfaces as toast/notification, kept in ActiveList).
 */
export interface Fire {
    "id": string;
    "ruleName": string;
    "message": string;
    "deviceId": string;
    "metric": Metric;
    "value": number;

    /**
     * info | warn | crit
     */
    "severity": string;
    "action": Action;
    "firedAt": number;
}

/**
 * Metric is a measurable dimension an alert rule can target.
 */
export enum Metric {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MetricUtilPct = "util_pct",
    MetricTempC = "temp_c",
    MetricPowerW = "power_w",
    MetricVRAMPct = "vram_pct",

    /**
     * bytes
     */
    MetricVRAMUsed = "vram_used",
};

/**
 * Operator compares sample value against Threshold.
 */
export enum Operator {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OpGt = "\u003E",
    OpGte = "\u003E\u003D",
    OpLt = "\u003C",
    OpLte = "\u003C\u003D",
};

/**
 * Rule is a persisted alert rule: entity × metric × threshold × action.
 * Entity mirrors DeviceInfo.ID ("gpu0") or "*" for all devices of a source
 * kind (e.g. "gpu0"*, "npu0"*, "*").
 */
export interface Rule {
    "id": string;
    "name": string;
    "metric": Metric;

    /**
     * device id suffix match; "*" = any; "proc" = per-process zombie rule
     */
    "entity": string;
    "operator": Operator;
    "threshold": number;
    "action": Action;
    "enabled": boolean;

    /**
     * min seconds between fires
     */
    "cooldownSec": number;
    "message"?: string;
}
