// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action is what an alert does when it fires.
 * @readonly
 * @enum {string}
 */
export const Action = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * in-app toast (frontend renders)
     */
    ActionToast: "toast",

    /**
     * desktop notification
     */
    ActionNotify: "notify",

    /**
     * suspend offender (zombie)
     */
    ActionAutoSuspend: "auto-suspend",

    /**
     * kill offender (zombie, double-confirm in future)
     */
    ActionAutoTerminate: "auto-terminate",
};

/**
 * Fire is an emitted alert (surfaces as toast/notification, kept in ActiveList).
 */
export class Fire {
    /**
     * Creates a new Fire instance.
     * @param {Partial<Fire>} [$$source = {}] - The source object to create the Fire.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("ruleName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ruleName"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("metric" in $$source)) {
            /**
             * @member
             * @type {Metric}
             */
            this["metric"] = Metric.$zero;
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("severity" in $$source)) {
            /**
             * info | warn | crit
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["action"] = Action.$zero;
        }
        if (!("firedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["firedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fire instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Fire}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fire(/** @type {Partial<Fire>} */($$parsedSource));
    }
}

/**
 * Metric is a measurable dimension an alert rule can target.
 * @readonly
 * @enum {string}
 */
export const Metric = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricUtilPct: "util_pct",
    MetricTempC: "temp_c",
    MetricPowerW: "power_w",
    MetricVRAMPct: "vram_pct",

    /**
     * bytes
     */
    MetricVRAMUsed: "vram_used",
};

/**
 * Operator compares sample value against Threshold.
 * @readonly
 * @enum {string}
 */
export const Operator = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OpGt: "\u003E",
    OpGte: "\u003E\u003D",
    OpLt: "\u003C",
    OpLte: "\u003C\u003D",
};

/**
 * Rule is a persisted alert rule: entity × metric × threshold × action.
 * Entity mirrors DeviceInfo.ID ("gpu0") or "*" for all devices of a source
 * kind (e.g. "gpu0"*, "npu0"*, "*").
 */
export class Rule {
    /**
     * Creates a new Rule instance.
     * @param {Partial<Rule>} [$$source = {}] - The source object to create the Rule.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("metric" in $$source)) {
            /**
             * @member
             * @type {Metric}
             */
            this["metric"] = Metric.$zero;
        }
        if (!("entity" in $$source)) {
            /**
             * device id suffix match; "*" = any; "proc" = per-process zombie rule
             * @member
             * @type {string}
             */
            this["entity"] = "";
        }
        if (!("operator" in $$source)) {
            /**
             * @member
             * @type {Operator}
             */
            this["operator"] = Operator.$zero;
        }
        if (!("threshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threshold"] = 0;
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["action"] = Action.$zero;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("cooldownSec" in $$source)) {
            /**
             * min seconds between fires
             * @member
             * @type {number}
             */
            this["cooldownSec"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rule(/** @type {Partial<Rule>} */($$parsedSource));
    }
}
