// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * AddSink registers an in-process consumer (e.g. HistoryService, AlertEngine)
 * that receives every sample; used instead of round-tripping through the
 * frontend event loop.
 */
export function AddSink(fn: any): $CancellablePromise<void> {
    return $Call.ByID(2513010868, fn);
}

/**
 * App returns the Wails application handle so sinks (history/alerts) can emit
 * frontend events from the polling goroutine.
 */
export function App(): $CancellablePromise<application$0.App | null> {
    return $Call.ByID(2164252067);
}

export function PauseSampling(): $CancellablePromise<void> {
    return $Call.ByID(2964520891);
}

export function ResumeSampling(): $CancellablePromise<void> {
    return $Call.ByID(3737787794);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1756339619, app);
}
