// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * AddSink registers an in-process consumer (e.g. HistoryService, AlertEngine)
 * that receives every sample; used instead of round-tripping through the
 * frontend event loop.
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function AddSink(fn) {
    return $Call.ByID(2513010868, fn);
}

/**
 * App returns the Wails application handle so sinks (history/alerts) can emit
 * frontend events from the polling goroutine.
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(2164252067).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PauseSampling() {
    return $Call.ByID(2964520891);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResumeSampling() {
    return $Call.ByID(3737787794);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1756339619, app);
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
