//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accelerator$0 from "../../../../../pmanage/pkg/accelerator/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as alerts$0 from "../../../../../pmanage/pkg/alerts/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "alert": $$createType0,
        "telemetry": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = alerts$0.Fire.createFrom;
const $$createType1 = accelerator$0.Sample.createFrom;

configure();
