// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as accelerator$0 from "../../../../../pmanage/pkg/accelerator/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as alerts$0 from "../../../../../pmanage/pkg/alerts/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "alert": alerts$0.Fire;
            "telemetry": accelerator$0.Sample;
        }
    }
}
