// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Info {
    "enabled": boolean;
    "address": string;
    "auth": boolean;
    "readOnly": boolean;
    "remoteAdj": boolean;
}
