// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is exposed to the frontend so the UI can reflect server-mode
 * state: whether we're headless over HTTP, and whether this session may
 * issue destructive verbs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Info>}
 */
export function Info() {
    return $Call.ByID(229318847).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LockAdmin re-enables read-only gating.
 * @returns {$CancellablePromise<void>}
 */
export function LockAdmin() {
    return $Call.ByID(312096523);
}

/**
 * UnlockAdmin toggles the process service out of read-only when the caller
 * presents the configured admin token. Mirrors the cookie-style handshake in
 * a service call so remote sessions can enable kill from the UI with the
 * right secret.
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function UnlockAdmin(token) {
    return $Call.ByID(2541728050, token);
}

// Private type creation functions
const $$createType0 = $models.Info.createFrom;
