// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is exposed to the frontend so the UI can reflect server-mode
 * state: whether we're headless over HTTP, and whether this session may
 * issue destructive verbs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Info(): $CancellablePromise<$models.Info> {
    return $Call.ByID(229318847);
}

/**
 * LockAdmin re-enables read-only gating.
 */
export function LockAdmin(): $CancellablePromise<void> {
    return $Call.ByID(312096523);
}

/**
 * UnlockAdmin toggles the process service out of read-only when the caller
 * presents the configured admin token. Mirrors the cookie-style handshake in
 * a service call so remote sessions can enable kill from the UI with the
 * right secret.
 */
export function UnlockAdmin(token: string): $CancellablePromise<void> {
    return $Call.ByID(2541728050, token);
}
