// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HostInfo {
    /**
     * Creates a new HostInfo instance.
     * @param {Partial<HostInfo>} [$$source = {}] - The source object to create the HostInfo.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("platformVer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platformVer"] = "";
        }
        if (!("kernelVer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kernelVer"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("uptimeSec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptimeSec"] = 0;
        }
        if (!("numCpu" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["numCpu"] = 0;
        }
        if (!("memTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memTotal"] = 0;
        }
        if (!("memUsed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memUsed"] = 0;
        }
        if (!("memPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memPct"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostInfo(/** @type {Partial<HostInfo>} */($$parsedSource));
    }
}
