// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HostInfo {
    "os": string;
    "platform": string;
    "platformVer": string;
    "kernelVer": string;
    "arch": string;
    "hostname": string;
    "uptimeSec": number;
    "numCpu": number;
    "memTotal": number;
    "memUsed": number;
    "memPct": number;
}
