// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface OpError {
    "pid": number;
    "action": string;
    "ok": boolean;
    "code": string;
    "message": string;
}

export interface ProcessInfo {
    "pid": number;
    "ppid": number;
    "name": string;
    "username": string;
    "status": string;
    "cpu": number;
    "memBytes": number;
    "memPct": number;
    "threads": number;
    "createTime": number;
    "elapsedSec": number;
}
