// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "../system/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function HostInfo(): $CancellablePromise<system$0.HostInfo> {
    return $Call.ByID(3046980130);
}

export function Kill(pid: number): $CancellablePromise<$models.OpError> {
    return $Call.ByID(4198434056, pid);
}

export function ListProcesses(): $CancellablePromise<$models.ProcessInfo[] | null> {
    return $Call.ByID(213771953);
}

/**
 * ReadOnly reports the current gating state.
 */
export function ReadOnly(): $CancellablePromise<boolean> {
    return $Call.ByID(2264072022);
}

export function Resume(pid: number): $CancellablePromise<$models.OpError> {
    return $Call.ByID(2367524171, pid);
}

export function SetPriority(pid: number, nice: number): $CancellablePromise<$models.OpError> {
    return $Call.ByID(1165254112, pid, nice);
}

/**
 * SetReadOnly toggles destructive-verb gating. Server mode defaults to
 * read-only unless an admin token has been configured and presented.
 */
export function SetReadOnly(ro: boolean): $CancellablePromise<void> {
    return $Call.ByID(2523761046, ro);
}

export function Suspend(pid: number): $CancellablePromise<$models.OpError> {
    return $Call.ByID(3881908100, pid);
}

export function Terminate(pid: number): $CancellablePromise<$models.OpError> {
    return $Call.ByID(755112423, pid);
}
