// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "../system/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<system$0.HostInfo>}
 */
export function HostInfo() {
    return $Call.ByID(3046980130).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} pid
 * @returns {$CancellablePromise<$models.OpError>}
 */
export function Kill(pid) {
    return $Call.ByID(4198434056, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProcessInfo[]>}
 */
export function ListProcesses() {
    return $Call.ByID(213771953).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ReadOnly reports the current gating state.
 * @returns {$CancellablePromise<boolean>}
 */
export function ReadOnly() {
    return $Call.ByID(2264072022);
}

/**
 * @param {number} pid
 * @returns {$CancellablePromise<$models.OpError>}
 */
export function Resume(pid) {
    return $Call.ByID(2367524171, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} pid
 * @param {number} nice
 * @returns {$CancellablePromise<$models.OpError>}
 */
export function SetPriority(pid, nice) {
    return $Call.ByID(1165254112, pid, nice).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetReadOnly toggles destructive-verb gating. Server mode defaults to
 * read-only unless an admin token has been configured and presented.
 * @param {boolean} ro
 * @returns {$CancellablePromise<void>}
 */
export function SetReadOnly(ro) {
    return $Call.ByID(2523761046, ro);
}

/**
 * @param {number} pid
 * @returns {$CancellablePromise<$models.OpError>}
 */
export function Suspend(pid) {
    return $Call.ByID(3881908100, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} pid
 * @returns {$CancellablePromise<$models.OpError>}
 */
export function Terminate(pid) {
    return $Call.ByID(755112423, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = system$0.HostInfo.createFrom;
const $$createType1 = $models.OpError.createFrom;
const $$createType2 = $models.ProcessInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
