// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Classified is the machine-readable result for one process.
 */
export interface Classified {
    "pid": number;
    "kind": Kind;

    /**
     * 0..1 aggregate confidence
     */
    "score": number;
    "hits": RuleHit[] | null;
}

/**
 * Kind groups processes into workload buckets.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindTraining = "training",
    KindInference = "inference",
    KindCodec = "codec",
    KindCrypto = "crypto",
    KindUnknown = "unknown",
};

/**
 * RuleHit records one matching classification rule: why the process was
 * assigned a bucket. Provenance = rule name; Weight = confidence-ish score.
 */
export interface RuleHit {
    "rule": string;

    /**
     * the matched token/path
     */
    "signal": string;

    /**
     * additive confidence contribution
     */
    "score": number;
}
