// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Classified is the machine-readable result for one process.
 */
export class Classified {
    /**
     * Creates a new Classified instance.
     * @param {Partial<Classified>} [$$source = {}] - The source object to create the Classified.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {Kind}
             */
            this["kind"] = Kind.$zero;
        }
        if (!("score" in $$source)) {
            /**
             * 0..1 aggregate confidence
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("hits" in $$source)) {
            /**
             * @member
             * @type {RuleHit[]}
             */
            this["hits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Classified instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Classified}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField3_0($$parsedSource["hits"]);
        }
        return new Classified(/** @type {Partial<Classified>} */($$parsedSource));
    }
}

/**
 * Kind groups processes into workload buckets.
 * @readonly
 * @enum {string}
 */
export const Kind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    KindTraining: "training",
    KindInference: "inference",
    KindCodec: "codec",
    KindCrypto: "crypto",
    KindUnknown: "unknown",
};

/**
 * RuleHit records one matching classification rule: why the process was
 * assigned a bucket. Provenance = rule name; Weight = confidence-ish score.
 */
export class RuleHit {
    /**
     * Creates a new RuleHit instance.
     * @param {Partial<RuleHit>} [$$source = {}] - The source object to create the RuleHit.
     */
    constructor($$source = {}) {
        if (!("rule" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rule"] = "";
        }
        if (!("signal" in $$source)) {
            /**
             * the matched token/path
             * @member
             * @type {string}
             */
            this["signal"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * additive confidence contribution
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleHit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuleHit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleHit(/** @type {Partial<RuleHit>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = RuleHit.createFrom;
const $$createType1 = $Create.Array($$createType0);
