// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service binds process→workload classification for the frontend. Signal
 * gathering reads live process state via gopsutil; Classify itself is pure.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Classify pid by first gathering live signals, then running the pure rules.
 */
export function ClassifyPID(pid: number): $CancellablePromise<$models.Classified> {
    return $Call.ByID(3405201940, pid);
}
