// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DeviceMetrics {
    "deviceId": string;
    "utilPct": number;
    "vramUsed": number;
    "vramTotal": number;
    "tempC": number;
    "powerW": number;
    "clockMhz": number;
    "clockMaxMhz": number;
    "fanPct": number;
    "status": string;

    /**
     * MinKernel mirrors DeviceInfo.MinKernel on samples so the UI can explain a
     * too-old kernel next to honest N/A cells (Linux drm fdinfo gates).
     */
    "minKernel"?: string;
    "memUtilRate"?: number;
    "encoderRate"?: number;
    "decoderRate"?: number;
    "powerMaxW"?: number;
    "effectiveLoad"?: number;

    /**
     * ValidFields is the JSON-serialized list of valid field names for the frontend.
     * Populated by sources alongside the bitmask so the UI knows which metrics to render.
     */
    "validFields"?: string[] | null;
}

/**
 * ProcUsage represents per-process accelerator usage.
 */
export interface ProcUsage {
    "pid": number;
    "name": string;
    "username"?: string;
    "deviceId": string;
    "vramUsed": number;
    "utilPct": number;
    "engine"?: { [_ in string]?: number } | null;
    "cpuUsage"?: number;
    "memResident"?: number;
    "memVirtual"?: number;

    /**
     * "graphical", "compute", "graphical+compute"
     */
    "type"?: string;

    /**
     * ValidFields is the JSON-serialized list of valid field names for the frontend.
     */
    "validFields"?: string[] | null;
}

export interface Sample {
    "devices": DeviceMetrics[] | null;
    "procs": ProcUsage[] | null;
    "ts": number;
}
