// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DeviceMetrics {
    /**
     * Creates a new DeviceMetrics instance.
     * @param {Partial<DeviceMetrics>} [$$source = {}] - The source object to create the DeviceMetrics.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("utilPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["utilPct"] = 0;
        }
        if (!("vramUsed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vramUsed"] = 0;
        }
        if (!("vramTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vramTotal"] = 0;
        }
        if (!("tempC" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tempC"] = 0;
        }
        if (!("powerW" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["powerW"] = 0;
        }
        if (!("clockMhz" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clockMhz"] = 0;
        }
        if (!("clockMaxMhz" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clockMaxMhz"] = 0;
        }
        if (!("fanPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fanPct"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * MinKernel mirrors DeviceInfo.MinKernel on samples so the UI can explain a
             * too-old kernel next to honest N/A cells (Linux drm fdinfo gates).
             * @member
             * @type {string | undefined}
             */
            this["minKernel"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceMetrics(/** @type {Partial<DeviceMetrics>} */($$parsedSource));
    }
}

export class ProcUsage {
    /**
     * Creates a new ProcUsage instance.
     * @param {Partial<ProcUsage>} [$$source = {}] - The source object to create the ProcUsage.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("vramUsed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vramUsed"] = 0;
        }
        if (!("utilPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["utilPct"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["engine"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcUsage}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("engine" in $$parsedSource) {
            $$parsedSource["engine"] = $$createField5_0($$parsedSource["engine"]);
        }
        return new ProcUsage(/** @type {Partial<ProcUsage>} */($$parsedSource));
    }
}

export class Sample {
    /**
     * Creates a new Sample instance.
     * @param {Partial<Sample>} [$$source = {}] - The source object to create the Sample.
     */
    constructor($$source = {}) {
        if (!("devices" in $$source)) {
            /**
             * @member
             * @type {DeviceMetrics[]}
             */
            this["devices"] = [];
        }
        if (!("procs" in $$source)) {
            /**
             * @member
             * @type {ProcUsage[]}
             */
            this["procs"] = [];
        }
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sample instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Sample}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField0_0($$parsedSource["devices"]);
        }
        if ("procs" in $$parsedSource) {
            $$parsedSource["procs"] = $$createField1_0($$parsedSource["procs"]);
        }
        return new Sample(/** @type {Partial<Sample>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = DeviceMetrics.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ProcUsage.createFrom;
const $$createType4 = $Create.Array($$createType3);
